string = "hi am rub"
string1 = "1 + 2="
print "1) ",(/am.*/).match(string),"\n"
print "2) ",(/.[aeiou].*/).match(string),"\n"
print "3) ",(/^am.*/).match(string),"\n"
print "4) ",/a/.match(string),"\n"
print "5) ",(/1\s\+\s2=/).match(string1),"\n"  # use backslash
print "6) ",(/am.*/).match(string),"\n"
print "7) ", /[0-9a-z].*/.match('09f'),"\n" #use range
print "8) ",/\d.+/.match("abcde1234abc"),"\n"
print "9) ", /ruby?/.match(string),"\n"
print "10) ",/ruby+/.match(string),"\n"
print "11) ",/\d{3}/.match("12345"),"\n"
print "12) ",/<.*>/.match("<abc><xyz>"),"\n"
print "13) ",/<.*?>/.match("<abc><xyz>"),"\n"
print "14) ",/[aeiou]\w+/.match("abcde"),"\n"
print "15) ",/rub|rul/.match(string),"\n"
string2 = "12345 abcde"
print string2.gsub!(/\D/,""),"\n"
